# Generated by Django 5.2 on 2025-05-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_simplebook_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplebook',
            name='title',
            field=models.CharField(help_text='Name of the book', max_length=255),
        ),
    ]
