# Generated by Django 5.2 on 2025-04-19 06:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('updated_at', models.DateField(auto_now=True)),
                ('publish_time', models.TimeField(auto_now_add=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=10)),
                ('content', models.TextField(blank=True, max_length=5000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('status_db', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=10)),
                ('phone', models.CharField(blank=True, help_text="Phone number must be in the format: '+999999999'", max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
