# Generated by Django 5.2 on 2025-04-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, max_length=4000)),
            ],
        ),
    ]
