# Generated by Django 5.2 on 2025-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
