# Generated by Django 5.1.4 on 2025-01-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusDash', '0002_book_post_question_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='simple_model',
            field=models.ManyToManyField(blank=True, to='octopusDash.simplemodel'),
        ),
    ]
