# Generated by Django 5.2 on 2025-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0002_post_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_path',
            field=models.FilePathField(blank=True, match='.*\\.txt$', null=True, path='/tmp'),
        ),
    ]
