# Generated by Django 5.2 on 2025-04-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0002_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=140)),
                ('desc', models.TextField(blank=True, max_length=4000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopusdash.field')),
            ],
        ),
    ]
