# Generated by Django 5.1.4 on 2025-01-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusDash', '0003_post_simple_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('display_fields', models.CharField(blank=True, max_length=2000)),
                ('model_form_fields', models.CharField(blank=True, max_length=2000)),
                ('model_form_exclude', models.CharField(blank=True, max_length=2000)),
                ('readonly_fields', models.CharField(blank=True, max_length=2000)),
                ('search_fields', models.CharField(blank=True, max_length=2000)),
                ('filter_fields', models.CharField(blank=True, max_length=2000)),
                ('paginate_by', models.PositiveIntegerField(default=10)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('icon', models.ImageField(blank=True, upload_to='app_icons/')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models_config', to='octopusDash.appconfig')),
            ],
        ),
    ]
