# Generated by Django 5.2 on 2025-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusdash', '0003_post_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='json_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
