# Generated by Django 5.1.4 on 2025-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusDash', '0007_resourcesaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='light', max_length=10)),
            ],
        ),
    ]
