# Generated by Django 5.1.4 on 2025-02-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopusDash', '0008_dashboardsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='site_id',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        ),
    ]
