# Generated by Django 5.1.4 on 2025-01-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appconfig_modelconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconfig',
            name='app',
        ),
        migrations.DeleteModel(
            name='AppConfig',
        ),
        migrations.DeleteModel(
            name='ModelConfig',
        ),
    ]
